const timezone = [
  "West African Time (WAT)",
  "Central African Time (CAT)",
  "Brazil Eastern Time (BET)",
  "Argentina Standard Time (AGT)",
  "Canada Newfoundland Time (CNT)",
  "Central Standard Time (CST)",
  "	Eastern Standard Time (EST)",
  "Indiana Eastern Standard Time (IST)",
  "Puerto Rico and US Virgin Islands Time (PRT)",
  "Phoenix Standard Time (PNT)",
  "Mountain Standard Time (MST)",
  "Pacific Standard Time (PST)",
  "Alaska Standard Time (AST)",
  "Hawaii Standard Time (HST)",
  "Midway Islands Time (MIT)",
  "New Zealand Standard Time (NST)",
  "Solomon Standard Time (SST)",
  "	Australia Eastern Time (AET)",
  "Australia Central Time (ACT)",
  "Japan Standard Time (JST)",
  "China Taiwan Time (CTT)",
  "	Vietnam Standard Time (VST)",
  "Bangladesh Standard Time (BST)",
  "	India Standard Time (IST)",
  "Pakistan Lahore Time (PLT)",
  "	Near East Time (NET)",
  "Middle East Time (MET)",
  "	Eastern African Time (EAT)",
  "(Arabic) Egypt Standard Time (ART)",
  "	Eastern European Time (EET)",
  "	European Central Time (ECT)",
  "Universal Coordinated Time (UCT)",
  "Greenwich Mean Time (GMT)",
];

export default timezone;
